# Automatically run tests on every commit to the repository and update the library version when commit message contains [tag:patch|minor|major].

name: Update Version

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    uses: credibil/build/.github/workflows/go-validate.yaml@main
    secrets: inherit

  version:
    needs: validate
    uses: credibil/build/.github/workflows/repo-version.yaml@main
    secrets: inherit